apiVersion: v1
kind: Pod
metadata:
  name: portal-noticias
spec:
  containers:
  - name: portal-noticias-container
    image: aluracursos/portal-noticias:1
  - name: portal-noticias-container2
    image: aluracursos/portal-noticias:1
