apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort
  selector:
    app: primeiro-pod
  ports:
  - port: 80
    # targetPort: 80 (se não explicitar a target, ele iraconsiderar que é a mesma de "port")
    nodePort: 30000
