apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    resources:
      limits:
        memory: 512Mi
        cpu: "1"
    volumeMounts:
    - mountPath: /volume-container
      name: primeiro-volume
  - name: jenkins-container
    image: jenkins/jenkins:lts
    resources:
      limits:
        memory: 512Mi
        cpu: "1"
    volumeMounts:
    - mountPath: /volume-container
      name: primeiro-volume
  volumes:
  - name: primeiro-volume
    hostPath:
      path: /C/Users/Andre/k8s/exemplos
      type: Directory
